# Generated by Django 5.2.6 on 2025-11-28 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto a cobrar')),
                ('entregado', models.BooleanField(default=False, verbose_name='¿Entregado al cliente?')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones al entregar')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de entrega')),
                ('diagnostico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='diagnostico.diagnostico', verbose_name='Diagnóstico asociado')),
            ],
        ),
    ]
