# Generated by Django 5.2.6 on 2025-11-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de dispositivo')),
                ('problema', models.TextField(verbose_name='Problema reportado')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de contacto')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo de contacto')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de recepción')),
                ('estado', models.CharField(choices=[('R', 'Recepcionado'), ('D', 'En diagnóstico'), ('T', 'En reparación'), ('L', 'Listo para entrega'), ('E', 'Entregado')], default='R', max_length=1, verbose_name='Estado del equipo')),
            ],
        ),
    ]
