# Generated by Django 5.2.6 on 2025-11-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del cliente'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('R', 'Recepcionado'), ('D', 'En diagnóstico'), ('L', 'Listo para entrega'), ('E', 'Entregado')], default='R', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del cliente'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(max_length=100, verbose_name='Tipo de equipo'),
        ),
    ]
