# Generated by Django 5.2.6 on 2025-11-28 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=100, verbose_name='Estudiante / Técnico')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('solucion', models.TextField(verbose_name='Solución aplicada')),
                ('estado', models.CharField(choices=[('E', 'En diagnóstico'), ('F', 'Finalizado')], default='F', max_length=1, verbose_name='Estado del diagnóstico')),
                ('fecha_diagnostico', models.DateTimeField(auto_now_add=True, verbose_name='Fecha diagnóstico')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='recepcion.equipo', verbose_name='Equipo recepcionado')),
            ],
        ),
    ]
