# Generated by Django 5.2.6 on 2025-11-29 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_estudiante_servicio'),
        ('recepcion', '0002_alter_equipo_correo_alter_equipo_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='precio_referencial',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='tipo_solucion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de solución'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.PositiveIntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del servicio'),
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('activo', models.BooleanField(default=True, verbose_name='Asignación activa')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='recepcion.equipo', verbose_name='Equipo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='diagnostico.estudiante', verbose_name='Estudiante / Técnico')),
            ],
            options={
                'verbose_name': 'Asignación de equipo',
                'verbose_name_plural': 'Asignaciones de equipos',
            },
        ),
    ]
